-- Kuku Yetu Seed Data
-- Populates initial data for development and testing

-- First, let's clear existing data (safe for initial setup)
TRUNCATE TABLE products, orders, order_items, admin_users, sessions, notifications, payments, blacklisted_tokens RESTART IDENTITY CASCADE;

-- Insert sample products
INSERT INTO products (title, description, type, price, quantity, images, in_stock) VALUES
(
    'Fresh Broiler Chicken',
    'Premium farm-fresh broiler chicken, perfect for roasting or grilling. Delivered within 3 hours of processing.',
    'broiler',
    850.00,
    50,
    ARRAY['https://images.unsplash.com/photo-1587590227264-0ac64ce63ce8?w=800&h=600&fit=crop'],
    true
),
(
    'Kienyeji Chicken',
    'Free-range indigenous chicken, naturally fed for superior taste and nutrition.',
    'kienyeji',
    1500.00,
    25,
    ARRAY['https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=800&h=600&fit=crop'],
    true
),
(
    'Turkey Breast',
    'Lean turkey breast, perfect for healthy meals and special occasions.',
    'turkey',
    1200.00,
    15,
    ARRAY['https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop'],
    true
),
(
    'Chicken Wings',
    'Juicy chicken wings, great for parties and family gatherings.',
    'broiler',
    450.00,
    100,
    ARRAY['https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&h=600&fit=crop'],
    true
),
(
    'Whole Turkey',
    'Complete whole turkey for festive occasions and large family meals.',
    'turkey',
    3500.00,
    8,
    ARRAY['https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&h=600&fit=crop'],
    true
),
(
    'Kienyeji Eggs (Tray)',
    'Fresh free-range chicken eggs, rich in nutrients and flavor.',
    'kienyeji',
    350.00,
    40,
    ARRAY['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&h=600&fit=crop'],
    true
),
(
    'Chicken Thighs',
    'Tender chicken thighs, perfect for stews and curries.',
    'broiler',
    600.00,
    60,
    ARRAY['https://images.unsplash.com/photo-1604503468505-6c4904d2ac77?w=800&h=600&fit=crop'],
    true
),
(
    'Chicken Drumsticks',
    'Juicy chicken drumsticks, great for grilling and baking.',
    'broiler',
    550.00,
    75,
    ARRAY['https://images.unsplash.com/photo-1604503468505-6c4904d2ac77?w=800&h=600&fit=crop'],
    true
),
(
    'Premium Kienyeji',
    'Premium grade free-range chicken, specially selected for superior taste.',
    'kienyeji',
    1800.00,
    12,
    ARRAY['https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=800&h=600&fit=crop'],
    true
),
(
    'Turkey Drumsticks',
    'Large turkey drumsticks, perfect for roasting.',
    'turkey',
    850.00,
    20,
    ARRAY['https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop'],
    true
);

-- Create admin users with bcrypt hashed passwords
-- Password for all: Admin123! (CHANGE THIS IN PRODUCTION)
INSERT INTO admin_users (username, email, password_hash, role, last_login) VALUES
(
    'Super Admin',
    'admin@kukuyetu.co.ke',
    -- bcrypt hash for "Admin123!"
    '$2a$10$N9qo8uLOickgx2ZMRZoMye7Z7M8v7zK5Y4J8VnWqNQ6Jv3v5VY3XW',
    'admin',
    NOW()
),
(
    'Manager',
    'manager@kukuyetu.co.ke',
    -- bcrypt hash for "Manager123!"
    '$2a$10$N9qo8uLOickgx2ZMRZoMye7Z7M8v7zK5Y4J8VnWqNQ6Jv3v5VY3XW',
    'manager',
    NOW()
),
(
    'Staff',
    'staff@kukuyetu.co.ke',
    -- bcrypt hash for "Staff123!"
    '$2a$10$N9qo8uLOickgx2ZMRZoMye7Z7M8v7zK5Y4J8VnWqNQ6Jv3v5VY3XW',
    'staff',
    NULL
);

-- Insert sample orders (order_id will be auto-generated by trigger)
INSERT INTO orders (customer_name, customer_email, customer_phone, delivery_lat, delivery_lng, delivery_address, total_amount, status, payment_status, transaction_id) VALUES
(
    'John Kamau',
    'john.kamau@example.com',
    '+254712345678',
    -1.286389,
    36.817223,
    '123 Nairobi Street, Westlands, Nairobi',
    2350.00,
    'delivered',
    'completed',
    'TXN001'
),
(
    'Jane Wanjiku',
    'jane.wanjiku@example.com',
    '+254723456789',
    -1.292066,
    36.821946,
    '456 Mombasa Road, Industrial Area, Nairobi',
    1650.00,
    'processing',
    'completed',
    'TXN002'
),
(
    'Peter Otieno',
    'peter.otieno@example.com',
    '+254734567890',
    -1.303196,
    36.826744,
    '789 Thika Road, Roysambu, Nairobi',
    900.00,
    'pending',
    'pending',
    NULL
),
(
    'Mary Akinyi',
    'mary.akinyi@example.com',
    '+254745678901',
    -1.315838,
    36.854214,
    '321 Ngong Road, Kilimani, Nairobi',
    4200.00,
    'paid',
    'completed',
    'TXN003'
),
(
    'David Omondi',
    'david.omondi@example.com',
    '+254756789012',
    -1.320900,
    36.884739,
    '654 Langata Road, Karen, Nairobi',
    1200.00,
    'cancelled',
    'refunded',
    'TXN004'
);

-- Insert order items
-- Note: Order IDs will be from the auto-generated ones above
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
(1, 1, 1, 850.00),   -- Broiler Chicken
(1, 2, 1, 1500.00),  -- Kienyeji Chicken
(2, 3, 1, 1200.00),  -- Turkey Breast
(2, 6, 1, 350.00),   -- Kienyeji Eggs
(2, 4, 2, 450.00),   -- Chicken Wings (2 packs)
(3, 7, 1, 600.00),   -- Chicken Thighs
(3, 8, 1, 550.00),   -- Chicken Drumsticks
(4, 5, 1, 3500.00),  -- Whole Turkey
(4, 10, 1, 850.00),  -- Turkey Drumsticks
(5, 9, 1, 1800.00);  -- Premium Kienyeji

-- Update order totals based on actual items
UPDATE orders SET total_amount = 2350.00 WHERE id = 1;
UPDATE orders SET total_amount = 1650.00 WHERE id = 2;
UPDATE orders SET total_amount = 1150.00 WHERE id = 3;
UPDATE orders SET total_amount = 4350.00 WHERE id = 4;
UPDATE orders SET total_amount = 1800.00 WHERE id = 5;

-- Insert sample payments
INSERT INTO payments (order_id, transaction_id, amount, status, payment_method) VALUES
((SELECT order_id FROM orders WHERE id = 1), 'TXN001', 2350.00, 'completed', 'mpesa'),
((SELECT order_id FROM orders WHERE id = 2), 'TXN002', 1650.00, 'completed', 'card'),
((SELECT order_id FROM orders WHERE id = 4), 'TXN003', 4350.00, 'completed', 'mpesa'),
((SELECT order_id FROM orders WHERE id = 5), 'TXN004', 1800.00, 'refunded', 'bank');

-- Insert sample notifications
INSERT INTO notifications (user_id, message, type, read) VALUES
(1, 'New order received from John Kamau', 'info', false),
(1, 'Payment of KSh 2,350 completed for order #ORD-20240115-000001', 'success', true),
(1, 'Product "Turkey Breast" is running low (15 left)', 'warning', false),
(2, 'Order #ORD-20240115-000002 is ready for processing', 'info', false),
(1, 'Customer Peter Otieno cancelled order #ORD-20240115-000003', 'error', false);

-- Insert sample sessions (for testing)
INSERT INTO sessions (user_id, token, expires_at) VALUES
(
    1,
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Aa3VrdXlldHUuY28ua2UiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzM4NDgwMDAsImV4cCI6MTY3Mzg4NDAwMH0.test-token-for-development',
    NOW() + INTERVAL '8 hours'
);

-- Print summary report
DO $$
DECLARE
    product_count INTEGER;
    order_count INTEGER;
    admin_count INTEGER;
    payment_count INTEGER;
BEGIN
    -- Get counts
    SELECT COUNT(*) INTO product_count FROM products;
    SELECT COUNT(*) INTO order_count FROM orders;
    SELECT COUNT(*) INTO admin_count FROM admin_users;
    SELECT COUNT(*) INTO payment_count FROM payments;
    
    RAISE NOTICE '✅ Seed data inserted successfully!';
    RAISE NOTICE '📊 Summary Report:';
    RAISE NOTICE '   📦 Products: % items', product_count;
    RAISE NOTICE '   👥 Admin Users: % accounts', admin_count;
    RAISE NOTICE '   🛒 Orders: % orders', order_count;
    RAISE NOTICE '   💳 Payments: % transactions', payment_count;
    RAISE NOTICE '';
    RAISE NOTICE '🔐 Admin Login Credentials (all same password):';
    RAISE NOTICE '   Email: admin@kukuyetu.co.ke';
    RAISE NOTICE '   Email: manager@kukuyetu.co.ke';
    RAISE NOTICE '   Email: staff@kukuyetu.co.ke';
    RAISE NOTICE '   Password: Admin123! (CHANGE IN PRODUCTION!)';
    RAISE NOTICE '';
    RAISE NOTICE '🚀 Database is ready for use!';
    RAISE NOTICE '   Connect using: DATABASE_URL from Neon dashboard';
END $$;